apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
        autoscaling.knative.dev/minScale: "1"
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: DATABASE_URL
          value: "postgres://{{ .Values.postgresql.postgresqlUsername }}:${POSTGRES_PASSWORD}@{{ .Chart.Name }}-postgresql/{{ .Values.postgresql.postgresqlDatabase }}"
        envFrom:
        - secretRef:
            name: {{ .Chart.Name }}-postgresql
        resources:
{{ toYaml .Values.resources | indent 12 }}
