[environments]
  [environments.development]
    name = "timesink-recorder"
    namespace = "timesink"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = ""
