apiVersion: v1
kind: ServiceAccount
metadata:
  name: timesink-source
  namespace: timesink # TODO: required?

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: timesink-source
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: timesink-source
    namespace: timesink # TODO: required?

---

apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ApiServerSource
metadata:
  name: timesink-source
  namespace: timesink # TODO: required?
spec:
  serviceAccountName: timesink-source
  resources:
    - apiVersion: "apps/v1"
      kind: Deployment
    - apiVersion: apps/v1
      kind: ReplicaSet
    - apiVersion: v1
      kind: Pod
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: timesink-recorder
    namespace: timesink # TODO: required?
